language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

git:
  submodules: false

before_script:
  - composer install --prefer-source
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpunit --configuration phpunit.travis.xml
  - phpcs --standard=PSR2 src/*

matrix:
  allow_failures:
    - php: hhvm
